name: Build and archive outline

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: gqcg-oss/latex-action@master
      with:
        root_file: outline.tex
        working_directory: outline
        latexmk_use_xelatex: true

    - name: Archive outline for develop
      uses: actions/upload-artifact@v2
      with:
        name: outline.pdf
        path: outline/outline.pdf
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}

    - name: Archive outline for PR
      uses: actions/upload-artifact@v2
      with:
        name: outline.pdf
        path: outline/outline.pdf
        retention-days: 5
      if: ${{ github.event_name == 'pull_request'}}
